/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import perpustakaan.Koneksi;
public class buku extends javax.swing.JFrame {

    /**
     * Creates new form buku
     */
    public buku() {
        initComponents();
        loadData();

        
    }

    private void loadData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Buku");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Jenis");      
    
    try{
            String sql="select* from buku";
            java.sql.Connection conn = (Connection) Koneksi.koneksiDB();
            java.sql.Statement stm =  conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
                table_buku.setModel(model);
            }}
            catch(Exception e){
                    System.out.println(e.getMessage());
                    }
            

    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id_buku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_pengarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_penerbit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tahun = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_jenis = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_buku = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create : Aprilan K Tamau");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 1, 770, 110));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID Buku");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 20));

        txt_id_buku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_id_buku.setToolTipText("");
        jPanel2.add(txt_id_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Judul");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 20));

        txt_judul.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_judul.setToolTipText("");
        jPanel2.add(txt_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pengarang");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        txt_pengarang.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_pengarang.setToolTipText("");
        jPanel2.add(txt_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Penerbit");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 20));

        txt_penerbit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_penerbit.setToolTipText("");
        jPanel2.add(txt_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tahun");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 20));

        txt_tahun.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_tahun.setToolTipText("");
        jPanel2.add(txt_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Jenis");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 20));

        txt_jenis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_jenis.setToolTipText("");
        jPanel2.add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 30));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel2.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 350));

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_buku);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 350));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 520, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            String sql = "Insert into buku(judul,pengarang,penerbit,tahun,jenis)VALUES('"+txt_judul.getText()+"','"+
                    txt_pengarang.getText()+"','"+txt_penerbit.getText()+"','"+txt_tahun.getText()+"','"+
                    txt_jenis.getText()+"')";
            
            
            java.sql.Connection conn = (Connection) Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        loadData();
       
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
         try {
            String sql = "DELETE from buku where id_buku='"+txt_id_buku.getText()+"'";
            java.sql.Connection conn = (Connection) Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        loadData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
           
            String sql = "update buku set judul = '"+txt_judul.getText()+"', pengarang = '"+
                    txt_pengarang.getText()+"', penerbit = '"+txt_penerbit.getText()+"',tahun = '"+txt_tahun.getText()+"', jenis = '"+
                    txt_jenis.getText()+"' where id_buku = '"+txt_id_buku.getText()+"' ";
            
            java.sql.Connection conn = (Connection) Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        loadData();
    }//GEN-LAST:event_btn_editActionPerformed

    private void table_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bukuMouseClicked
       int baris = table_buku.rowAtPoint(evt.getPoint());
       String id_buku = table_buku.getValueAt(baris, 0).toString();
       txt_id_buku.setText(id_buku);
       String judul = table_buku.getValueAt(baris, 1).toString();
       txt_judul.setText(judul);
        String pengarang = table_buku.getValueAt(baris, 2).toString();
       txt_pengarang.setText(pengarang);
        String penerbit = table_buku.getValueAt(baris, 3).toString();
       txt_penerbit.setText(penerbit);
       String tahun = table_buku.getValueAt(baris, 4).toString();
       txt_tahun.setText(tahun);
       String jenis = table_buku.getValueAt(baris, 5).toString();
       txt_jenis.setText(jenis);
    }//GEN-LAST:event_table_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_buku;
    private javax.swing.JTextField txt_id_buku;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_tahun;
    // End of variables declaration//GEN-END:variables
}
